### PR TITLE
fix: background integration

### LINKED ISSUE #46: [feat] Add toogle for ligth and dark theme management
#### **Objective**:
Introduce a toggle on the navbar to switch between dark mode and light mode. The background should dynamically change based on the selected mode.

---

#### **Tasks**:

1. **Add Toggle to Navbar**:
   - Create a **Dark/Light Mode toggle** in the navbar.
   - Ensure the toggle is accessible and matches the app’s style.

2. **Background Integration**:
   - The current background is managed through a **background component**. Connect the toggle functionality to dynamically switch between:
     - **Dark mode background** (current version).
     - **Light mode background** (new version).

3. **Create Light Version of Background**:
   - Design a light version of the background:
     - Use a **white background**.
     - Retain the **stars animation** for visual continuity.

4. **Toggle Functionality**:
   - Implement logic for the toggle to switch between the dark and light backgrounds.
   - Ensure a smooth transition when switching modes.

---

#### **Deliverables**:
- The **Dark/Light mode toggle** should:
  - Dynamically update the background.
  - Persist the user’s preference (optional).

- The **Light mode background** should:
  - Use a white base color.
  - Include the stars animation.

---

#### **Notes**:
- Test the toggle functionality and background transitions on different devices and screen sizes.
- When the PR is ready for review, include:
  - **Images of the changes** (dark mode and light mode backgrounds).
  - **Reference the issue number** in the PR description.

### PR DESCRIPTION
**Pull request by sonkeydotcom**
close #46

### CODE REVIEW

**Review by jsandinoDev — CHANGES_REQUESTED** [review]
- Problem with font color of header after click tooggle button
- Background color still the same 

Screenshot 2025-01-23 at 6 51 01 PM

**Comment by jsandinoDev** [comment]
When you fix that, can you please add an screenshot of the home screen?

**Comment by sonkeydotcom** [comment]
Screen Shot 2025-01-24 at 1 58 30 AM
Screen Shot 2025-01-24 at 1 58 42 AM

**Comment by jsandinoDev** [comment]
Can you keep the original color for the dark theme of the app? And for the light theme can you use #dbd9d9 (it is a white but not that bright)

**Comment by sonkeydotcom** [comment]
its done

**Review by jsandinoDev — APPROVED** [review]
LGTM

File: packages/nextjs/app/page.tsx [hunk 1]
```diff
@@ -16,7 +16,7 @@ const Home: NextPage = () => {
 
   return (
     <>
-      <div className="relative flex justify-center items-center min-h-screen text-white overflow-hidden">
+      <div className="relative flex justify-center items-center min-h-scree overflow-hidden">
```
Comment (Ilialtes) [inline packages/nextjs/app/page.tsx:19]: min-h-scree?

File: packages/nextjs/components/ToggleMode.tsx [hunk 2]
```diff
@@ -0,0 +1,29 @@
+import React from "react";
+import { MoonIcon, SunIcon } from "@radix-ui/react-icons";
+import { useTheme } from "next-themes";
+
+const ToggleMode = () => {
+  const { setTheme, theme } = useTheme(); 
+  const isDarkMode = theme === "dark"; 
+
+  const toggleMode = () => {
+    // const newMode = isDarkMode ? "light" : "dark";
```
Comment (Ilialtes) [inline packages/nextjs/components/ToggleMode.tsx:10]: remove unused comments

File: packages/nextjs/components/starryBackground/_components/StarryBackground.tsx [hunk 3]
```diff
@@ -2,7 +2,7 @@ import React from "react";
 
 const StarryBackground = () => {
   return (
-    <div className="absolute inset-0 bg-gradient-to-b from-[#243B55] to-[#141E30] overflow-hidden">
+    <div className="absolute inset-0 overflow-hidden"> {/* bg-gradient-to-b from-[#243B55] to-[#141E30] */}
```
Comment (Ilialtes) [inline packages/nextjs/components/starryBackground/_components/StarryBackground.tsx:5]: remove comments

File: packages/nextjs/styles/globals.css [hunk 4]
```diff
@@ -40,6 +40,7 @@ p {
   filter: blur(229px);
   position: absolute;
   top: 0;
+  display: none /* Hidden */
```
Comment (Ilialtes) [inline packages/nextjs/styles/globals.css:43]: remove comments

File: packages/nextjs/styles/globals.css [hunk 5]
```diff
@@ -49,6 +50,7 @@ p {
   position: absolute;
   top: 0;
   right: 0;
+  display: none /* Hidden */
```
Comment (Ilialtes) [inline packages/nextjs/styles/globals.css:53]: remove comments

File: packages/nextjs/styles/globals.css [hunk 6]
```diff
@@ -100,6 +102,7 @@ p {
   border-radius: 630px;
   background: #7353d2;
   filter: blur(229px);
+  display: none /* Hidden */
```
Comment (Ilialtes) [inline packages/nextjs/styles/globals.css:105]: remove comments

File: packages/nextjs/styles/globals.css [hunk 7]
```diff
@@ -109,6 +112,7 @@ p {
   position: absolute;
   top: 0;
   right: 0;
+  display: none /* Hidden */
```
Comment (Ilialtes) [inline packages/nextjs/styles/globals.css:115]: remove comments

**Review by Ilialtes — CHANGES_REQUESTED** [review]

File: packages/nextjs/styles/globals.css (hunk 7 above)
Comment (sonkeydotcom) [reply packages/nextjs/styles/globals.css]: Done!

**Review by Ilialtes — APPROVED** [review]
LGTM!
