### PR TITLE
FIX: Recent Flips & Transaction history responsiveness

### LINKED ISSUE #103: [bug] Adjust Recent Flips &&  Transaction History mobile responsive
#### **Description**  
Improve the mobile responsiveness of the ```packages/nextjs/app/recentflips/_components/RecentFlip.tsx``` && ```packages/nextjs/app/leaderboard/_components/Leaderboard.tsx```  sections to ensure proper layout and alignment.  

#### **Current Issues**  
- **Recent Flips (Incorrect Layout)**  
  Wrong Recent Flips  

- **Transaction History (Incorrect Layout)**  
  Wrong Transaction History  

#### **Reference for Correct Layout**  
- The **Leaderboard** section has a proper mobile layout. Use it as a reference.  
  Good Example - Leaderboard

### PR DESCRIPTION
**Pull request by lauchaves**
## Pull Request Title

FIX: Recent Flips & Transaction history responsiveness

## Description
Updated styles to fix responsiveness in Recent Flips & Transaction History.  

## Related Issues
Closes #103 

## Changes Made
- [x] Improve the mobile responsiveness of the packages:
  - [x] `packages/nextjs/app/recentflips/_components/RecentFlip.tsx`
  - [x] `packages/nextjs/app/leaderboard/_components/Leaderboard.tsx`

## Checklist
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] Documentation has been updated accordingly

## Screenshots

https://www.loom.com/share/f0c1602298a743b2b86216639b1a6b06?sid=d95e7cef-8af7-4ea4-ace7-dbe87dd7672f

image

image

## Additional Notes
N/A

### CODE REVIEW

**Review by jsandinoDev — APPROVED** [review]
LGTM!

File: packages/nextjs/app/history/_components/TransactionHistory.tsx [hunk 1]
```diff
@@ -20,6 +20,26 @@ export default function TransactionHistory({
     router.back();
   };
 
+  // Function to shorten addresses in mobile view
```
Comment (Ilialtes) [inline packages/nextjs/app/history/_components/TransactionHistory.tsx:23]: remove comments

File: packages/nextjs/app/history/_components/TransactionHistory.tsx [hunk 2]
```diff
@@ -20,6 +20,26 @@ export default function TransactionHistory({
...
+  const shortenAddress = (address: string) => {
+    return address.slice(0, 6) + "..." + address.slice(-4);
+  };
+
+  // Function to process message and replace addresses
```
Comment (Ilialtes) [inline packages/nextjs/app/history/_components/TransactionHistory.tsx:28]: remove comments

**Review by Ilialtes — CHANGES_REQUESTED** [review]

**Review by Ilialtes — COMMENTED** [review]
Solve conflicts

**Comment by lauchaves** [comment]
@Ilialtes comments addressed

**Review by jsandinoDev — APPROVED** [review]

**Review by Ilialtes — APPROVED** [review]
